#ifndef _HLBR_DECODE_URI_H_
#define _HLBR_DECODE_URI_H_

#define HTTP_METHODS		0x0001
#define WEBDAV_METHODS		0x0010
#define WEBDAV_EX_METHODS	0x0100
#define MS_WEBDAV_METHODS	0x1000

#define HTTP_CONTENT_REGEX "[[:print:]]*?HTTP/1\\.[01]"

#define HTTP_METHODS_REGEX "(OPTIONS|GET|HEAD|POST|PUT|DELETE|TRACE|CONNECT)"HTTP_CONTENT_REGEX

#define WEBDAV_METHODS_REGEX "(COPY|MOVE|PROP(FIND|PATCH)|(UN)?LOCK|MKCOL|NOTIFY|POLL)"HTTP_CONTENT_REGEX
#define WEBDAV_EX_METHODS_REGEX "(VERSION-CONTROL|REPORT|CHECKIN|(UN)?CHECKOUT|UPDATE|LABEL|MERGE|BASELINE-CONTROL|MKACTIVITY)"HTTP_CONTENT_REGEX

#define MS_WEBDAV_METHODS_REGEX "(B(COPY|MOVE|DELETE|PROP(FIND|PATCH))|X-MS-ENUMATTS|(UN)?SUBSCRIBE)"HTTP_CONTENT_REGEX

typedef struct uridata {
	char	*decoded;
	int	decoded_size;
} URIData;

int InitDecodeURI();

#endif
