#ifndef _HLBR_DECODE_URI_H_
#define _HLBR_DECODE_URI_H_

/* Belive-me, Apache and ISS are very very non-conforming  */
#define HTTP_CONTENT_REGEX " +[!-~]+ +[!-~]+"

#define HTTP_METHODS_REGEX "(OPTIONS|GET|HEAD|POST|PUT|DELETE|TRACE|CONNECT)"HTTP_CONTENT_REGEX

#define WEBDAV_METHODS_REGEX "(COPY|MOVE|PROP(FIND|PATCH)|(UN)?LOCK|MKCOL|NOTIFY|POLL)"HTTP_CONTENT_REGEX

#define WEBDAV_EX_METHODS_REGEX "(VERSION-CONTROL|REPORT|CHECKIN|(UN)?CHECKOUT|UPDATE|LABEL|MERGE|BASELINE-CONTROL|MKACTIVITY)"HTTP_CONTENT_REGEX

#define MS_WEBDAV_METHODS_REGEX "(B(COPY|MOVE|DELETE|PROP(FIND|PATCH))|X-MS-ENUMATTS|(UN)?SUBSCRIBE)"HTTP_CONTENT_REGEX

typedef struct uridata {
	char	*decoded;
	int	decoded_size;
} URIData;

int InitDecodeURI();

#endif
